# mpv-lazy / mpv_PlayKit 将 imput.conf 识别成菜单栏
# "#" 开头表示没有快捷键 仅在菜单栏展示
# 快捷键开头表示有快捷键 并在菜单栏展示
# "#!" 的注解表示在菜单栏中的显示名称和分级

# 修改原则是尽量减少记忆量 大部分操作由界面化菜单栏触发
# - 正则匹配 "^ [^ ]* " 将快捷键一键替换 "#"
# - 正则匹配 "^#[^# ]*[ ]+" 统一命令缩进 "#           "
# - 正则匹配 "#           #! " 进行修正
#   - 替换为 "#           ignore                                                #! "
# - 正则匹配 "ignore$" 进行修正
#   - 替换为 "ignore                                                #! 工具 > ---"

### =========================== 映射菜单替换如下 ===========================

 LEFT       seek -1 ; script-message-to uosc flash-elements timeline                  # 播放 > 后退 1s
 RIGHT      seek  1 ; script-message-to uosc flash-elements timeline                  # 播放 > 前进 1s
 DOWN       no-osd add volume -1 ; script-message-to uosc flash-elements volume       # 播放 > 音量 -
 UP         no-osd add volume  1 ; script-message-to uosc flash-elements volume       # 播放 > 音量 +
 -          no-osd add speed -0.5 ; script-message-to uosc flash-elements speed       # 播放 > 速度 -
 =          no-osd add speed  0.5 ; script-message-to uosc flash-elements speed       # 播放 > 速度 +
#           ignore                                                #! 播放 > ---
 l          ab-loop                                               #! 播放 > 设置/清除 AB循环点
 ,          frame-back-step                                       #! 播放 > 上一帧
 .          frame-step                                            #! 播放 > 下一帧
#           ignore                                                #! 播放 > ---
 a          add audio-delay -0.1                                  #! 播放 > 音频预载 100ms
 d          add audio-delay  0.1                                  #! 播放 > 音频延迟 100ms
 w          add sub-delay -0.1                                    #! 播放 > 字幕预载 100ms
 s          add sub-delay  0.1                                    #! 播放 > 字幕延迟 100ms
#           ignore                                                #! 播放 > ---
 r          set audio-delay 0 ; set sub-delay 0                   #! 播放 > 重置 音频与字幕同步


 k          script-binding uosc/keybinds                          #! 工具 > ※ 按键绑定列表
 i          script-binding stats/display-stats                    #! 工具 > 限时显示统计信息
 I          script-binding stats/display-stats-toggle             #! 工具 > 常驻显示统计信息
 `          script-binding commands/open                          #! 工具 > 显示OSD命令行（控制台）
 o          script-binding uosc/menu                              #! 工具 > 打开uosc菜单
 O          context-menu                                          #! 工具 > 打开原生菜单
#           ignore                                                #! 工具 > ---

### =========================== 不映射菜单替换如下 ===========================

 MBTN_LEFT      ignore               # <无操作> [左键-单击]
 MBTN_LEFT_DBL  cycle fullscreen     # 切换 全屏/窗口 [左键-双击]
 MBTN_RIGHT     cycle pause          # 切换 暂停/播放 [右键-单击]

 WHEEL_UP       no-osd add volume  2 ; script-message-to uosc flash-elements volume        # 音量 +
 WHEEL_DOWN     no-osd add volume -2 ; script-message-to uosc flash-elements volume        # 音量 -

 SPACE          cycle pause          # 切换 暂停/播放 [空格键]
 ENTER          cycle fullscreen     # 切换 全屏/窗口 [回车键]
 ESC            set fullscreen no    # 退出 全屏状态  [ESC]
